name: wesmart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_auth_web: ^5.13.4
  lottie: ^3.1.3
  flutter_email_sender: ^5.0.3
  http: ^1.2.2
  google_sign_in: ^5.4.0
  url_launcher: ^6.1.10
  mailer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/Image.png
      - assets/image2.webp
      - assets/image copy.png
      - assets/undraw_welcome_cats_thqn.png
      - assets/avater.png